### PR TITLE
Potential fix for issue #106

### PR DESCRIPTION
**Pull request by rscrimojr**

### CODE REVIEW

**Comment by rscrimojr** [comment]
@timofurrer Not sure why `@step("Given a user named Bruce")` is failing in the CI checks but I just tried that in my environment with this change and it worked fine.

**Comment by timofurrer** [comment]
> @timofurrer I see why @step("a user named {:w}") is failing in the CI checks. When using @step with step > sentence "Given a user named Bruce" this will fail when not using the @given decorator in my experience. Is this supposed to work?

Yes, you are right. See #61 

`parse.search` uses `re.search` and `parse.parse` uses `re.match` internally - that's why they return different results.

We could use `parse.parse` but we don't use `re.match` for regex step patterns which I see as an inconsistency which is to avoid. And we might break a lot of existing step patterns because we change the API.

I'm not entirely sure what to do with this issue yet. I'll come back to it! 
Can you work with the work around for a while?

**Comment by rscrimojr** [comment]
Yes, I get that.  Just a thought, can't you just stack the decorators for the different patterns for technically the same sentences that uses the same code.  I am doing that for different verbs for the same sentences in my test code and it is working as expected.  Does `@step` remove all possible verbs at the beginning of the sentences?  I am stacking because I could not get step to work with `Given`, `When` and `Then` sentences.  I guess the better question is what is the preferred way to address multiple sentences the has the same code? A `@step` with a complex regex or some other way?  I am interested in your take because I am not sure the docs address this situation?

```
e.g.
@step(r'a user named {:w}')  # for And
@given(r'a user named {:w}')   # for Given
def my_step(step, username):
   ...
```

I personally believe explicit is better than implicit.  There is no magic then.  I get that `@step` removes `^and` and `@given` removes `^given`, etc. it the sentences start with those "verbs".

I can use regexes in the meantime.

Timo, thanks for being so responsive and helpful.

Robert

**Comment by rscrimojr** [comment]
I should probably close this PR.   I don't think radish needs to change.   I think that `parse.search` is not working correctly in this case.  Let me know what you want to do.

**Comment by timofurrer** [comment]
> I should probably close this PR. I don't think radish needs to change. 

Agreed. I'm going to close this for now then.

**Pull request closed without merging**
