### PR TITLE
WIP: Feature/support multiple tags on single line

### PR DESCRIPTION
**Pull request by fliiiix**
- Needs CI branch fixed & merged
- Needs tests
- Update docs

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @fliiiix, are you still working on the PR?
Please let me know if you are not, I would like to try implementing the tests for the feature.
Thanks.

**Comment by timofurrer** [comment]
@vchrombie the current `master` branch is the start of an entirely new parser based on an EBNF parser using lark. 

AFAIK, currently it wouldn't support multiple tags on a single line, so you'd have to start from scratch there.

**Comment by fliiiix** [comment]
@vchrombie I think i kinda forgot about this so feel free to take this as a start

from my comments i would guess something worked with this branch but not to sure tbh ^^

**Comment by fliiiix** [comment]
replaced by https://github.com/radish-bdd/radish/pull/451

**Pull request closed without merging**
