### PR TITLE
Enhancement #124

### PR DESCRIPTION
**Pull request by rscrimojr**

### CODE REVIEW

**Comment by timofurrer** [comment]
Looks good so far.
Could you provide at least a functional test? For example you could in your steps depend on a specific user data input.

**Comment by rscrimojr** [comment]
Yes.  Let me look into it and I will commit some tests and docs as soon as I can.

**Comment by timofurrer** [comment]
The docs and tests look good so far. Have you noticed that it's failing on Travis?

**Comment by rscrimojr** [comment]
@timofurrer I have added a test and updated the documentation for commandline.rst.  Let me know if you need anything else.

**Comment by rscrimojr** [comment]
@timofurrer I fixed the issue with travis with this commit https://github.com/radish-bdd/radish/pull/127/commits/1b0eb59804ab781ecc1073b1d9afe9dd3a40442f

**Comment by rscrimojr** [comment]
@timofurrer I do have one concern that I am not sure how to correct without hacks.  If `-u` or `--user-data` is not specified on the command-line, if you inspect world.config.user_data you will get an empty list from `docopts`.  So, with no data provided on the command-line, the extension will not initialize.  I would like to initialize the `world.config.user_data` to a empty dictionary.  However a pythonic check for contents works either way. E.g. `if world.config.user_data: ...`  If this bothers you, do you have a solution for this ?

**Comment by rscrimojr** [comment]
@timofurrer Well,  I thought about it and the answer was right there.  I changed `LOAD_IF` statement to `LOAD_IF = staticmethod(lambda config: True)` and it is correct now.

**Comment by rscrimojr** [comment]
No problem.  You're very welcome. Thanks.  I am glad I can help out. 👍 🍻

**Pull request merged**
