### PR TITLE
fix argument parsing for --scenarios

### PR DESCRIPTION
**Pull request by fliiiix**

### CODE REVIEW

**Comment by timofurrer** [comment]
Tests would be awesome :)

**Comment by fliiiix** [comment]
to quote rkh: "don't include tests. tests just bloat the code base. just commit, the users will complain if you break anything."

**Comment by fliiiix** [comment]
Ok added some tests **BUT**  two things if not all scenarios are run this is considered a failure? Is this by design? (This is not what I would expect)

And the second thing is to use the `-s=1` syntax was only in the help for the stable radish so question is if we want to support that on master since `click` does not show it like this in the help `-s, --scenarios TEXT`

**Comment by fliiiix** [comment]
no intention to do that anytime soon

**Pull request closed without merging**
