### PR TITLE
Add more tests to increase coverage

### PR DESCRIPTION
**Pull request by vchrombie**
This PR adds some more tests targeting the gherkin formatter aiming to increase the test coverage.

### CODE REVIEW

**Comment by timofurrer** [comment]
Can you please rebase? The trigger to run workflows on PR were missing ...

**Comment by vchrombie** [comment]
> Can you please rebase? The trigger to run workflows on PR were missing ...

Sure, I was actually wondering for not seeing the workflows. Now it makes sense.

**Comment by vchrombie** [comment]
Hi @timofurrer, I have rebased the branch. Once you approve the workflows, the CI gets triggered.
Please let me know if you have any comments related to the PR.

**Comment by vchrombie** [comment]
Looks like the tests are passing, but there is some problem with the codecov.

**Comment by fliiiix** [comment]
Would it make sense to port back some of these tests to stable? :eyes: @timofurrer (since im not to optimistic that we do a radish 1.0 anytime soon)

**Comment by vchrombie** [comment]
@timofurrer Do you need any help from my side for the review of this PR? Please let me know if I can help in any way.

**Comment by timofurrer** [comment]
@vchrombie No, I don't think - we need to fix codecov first ..

**Comment by vchrombie** [comment]
> @vchrombie can you rebase your branch?

Sure, let me do it right away

**Comment by vchrombie** [comment]
https://github.com/vchrombie/radish/actions/runs/1987749058

**Comment by fliiiix** [comment]
@timofurrer anything which prevents this from beeing merged?

**Comment by timofurrer** [comment]
Nope, just too busy with other things. Merging now, thanks for the ping and contributon 🎉

**Comment by vchrombie** [comment]
Thanks @timofurrer for merging it and @fliiiix for the reminder ping! :)

**Pull request merged**
