### PR TITLE
Python 2.6 Compatibility fixes

### PR DESCRIPTION
**Pull request by svdgraaf**
For a project, I'm forced to use Python 2.6 (don't ask), these are some small fixes that will fix Python2.6 compatibility.

I know 2.6 is ancient, but I would love to see these changes being added for this awesome project :)

### CODE REVIEW

**Comment by timofurrer** [comment]
Thanks for the PR.
Indeed, Python 2.6 is ancient and I won't ask .... Please upgrade though ...

I'm willing to merge this patch. However, `td.total_seconds()` and `td.seconds()` are not in all cases equivalent. The real equivalent would be:

```python
(td.microseconds + (td.seconds + td.days * 24 * 3600) * 10**6) / 10**6
```

I'm more interested in the microseconds than the days here. Could you please fix that?

**Comment by timofurrer** [comment]
And if you want to support Python 2.6 you should also add Python 2.6 to the travis and tox test matrices.

**Comment by timofurrer** [comment]
I'm going to reject this PR since I want to drop python 2 support any ways completely for future releases. I'll just back port some bugs ... maybe.

Thanks for your contribution though :beers:

**Comment by svdgraaf** [comment]
@timofurrer yes, I understand :) keep it up and have a good one 👍🏻🍻

**Pull request closed without merging**
